=== pumiko/studies-and-training/Web-Map-Services/2_2_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:simpleType name="ISBNType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{10}"/>
      <xs:pattern value="[0-9]{13}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:element name="biblioteczka">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ksiazka" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="sygnatura" type="xs:string" minOccurs="1" maxOccurs="1"/>
              <xs:element name="autor" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="tytul" type="xs:string" minOccurs="1" maxOccurs="1"/>
              <xs:element name="podtytul" type="xs:string" minOccurs="0" maxOccurs="1"/>
              <xs:element name="wydanie" type="xs:positiveInteger" minOccurs="0" maxOccurs="1"/>
              <xs:element name="wydawnictwo" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="isbn" type="ISBNType" maxOccurs="1"/>
              <xs:element name="opis" type="xs:string" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== pumiko/studies-and-training/Web-Map-Services/2_2_XML_library.xml
<?xml version="1.0" encoding="UTF-8"?>

<biblioteczka xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="2_2_schema.xsd">

  <ksiazka>
    <sygnatura>MS01</sygnatura>
    <autor>Tolkien, J. R. R.</autor>
    <tytul>Władca Pierścieni</tytul>
    <wydanie>2001</wydanie>
    <wydawnictwo>Zysk i S-ka</wydawnictwo>
    <isbn>8372981086</isbn>
    <opis>
    Książka opowiada o Wojnie o Pierścień, której wynik zależy od powodzenia misji niziołka Frodo Bagginsa. Hobbit musi zniszczyć tytułowy Pierścień, a dokonać tego może tylko w Mordorze, królestwie Saurona. W czasie jego wędrówki w Śródziemiu rozgrywają się liczne pojedynki, a ludzie, wspomagani przez czarodzieja Gandalfa, starają się stawić czoła cieniowi, który idzie od wschodu.
    </opis> 
  </ksiazka>
  
  <ksiazka>
    <sygnatura>MS02</sygnatura>
    <autor>Zafon, C. R.</autor>
    <tytul>Gra Anioła</tytul>
    <wydanie>2008</wydanie>
    <wydawnictwo>Warszawskie Wydawnictwo Literackie MUZA SA</wydawnictwo>
    <isbn>9788374956000</isbn>
    <opis>
    Młody, zdolny pisarz, otrzymuje wyjątkową ofertę napisania książki, która ma stać się nową religią. David Martin musi dowiedzieć się kim jest tajemniczy wydawca lecz na każdym kroku czyhają na niego niebezpieczeństwa. Zafon ponownie przenosi nas do Cmentarzyska Zapomnianych Książek znajdującego się w mrocznej Barcelonie lat dwudziestych XX w. W książce przyjaźń, miłość, talent i ambicja przeplaatają się z tajemnicą i grozą.
    </opis>
  </ksiazka>
  
  <ksiazka>
    <sygnatura>MS03</sygnatura>
    <autor>Christie, A.</autor>
    <tytul>I nie było już nikogo</tytul>
    <wydanie>2014</wydanie>
    <wydawnictwo>Wydawnictwo Dolnośląskie. Oddział Publicat</wydawnictwo>
    <isbn>9788327151797</isbn>
    <opis>
    Inny tytuł książki to "Dziesięciu Murzynków" lub "Dziesięciu Żołnierzyków". Dziesięć obcych sobie osób otrzymuje zaproszenie na odizolowaną od świata wyspę. W swoich pokojach znajdują fragmenty dziecięcego wierszyka, lecz tym razem dotyczy on ich losu. Kto jest odpowiedzialny za śmierć kolejnych osób? Czy ktokolwiek ocaleje z tej makabrycznej zabawy?
    </opis> 
  </ksiazka> 
  
</biblioteczka>
